package Options;

import java.util.Random;

public enum Civics {
    CUTTHROAT_POLITICS,
    EFFICIENT_BUREAUCRACY,
    ENVIRONMENTALIST,
    FUNCTIONAL_ARCHITECTURE,
    MINING_GUILDS,
    AGRARIAN_IDYLL,
    ARISTOCRATIC_ELITE,
    BEACON_OF_LIBERTY,
    CITIZEN_SERVICE,
    CORPORATE_DOMINION,
    CORVEE_SYSTEM,
    DISTINGUISHED_ADMIRALTY,
    EXALTED_PRIESTHOOD,
    FEUDAL_SOCIETY,
    FREE_HAVEN,
    IDEALISTIC_FOUNDATION,
    IMPERIAL_CULT,
    INWARD_PERFECTION,
    MERITOCRACY,
    NATIONALISTIC_ZEAL,
    PARLIAMENTARY_SYSTEM,
    PHILOSOPHER_KING,
    POLICE_STATE,
    SHADOW_COUNCIL,
    SLAVER_GUILDS,
    TECHNOCRACY,
    WARRIOR_CULTURE,
    CATALYTIC_PROCESSING,
    IDYLLIC_BLOOM,
    ASCENSIONISTS,
    FANATIC_PURIFIERS,
    MASTERFUL_CRAFTERS,
    PLEASURE_SEEKERS,
    POMPOUS_PURISTS,
    BARBARIC_DESPOILERS,
    BYZANTINE_BUREUCRACY,
    MERCHANT_GUILDS,
    SHARED_BURDENS,
    DIPLOMATIC_CORPS,
    DEATH_CULT,
    MEMORIALISTS,
    REANIMATORS,
    ANGLERS,
    MUTAGENIC_SPAS,
    RELENTLESS_INDUSTRIALISTS,
    SCAVENGERS;

    public static final Random civicsGen = new Random();
    private static final Civics[] civics = values();

    public static Civics randomCivics() {
        return civics[civicsGen.nextInt(civics.length)];
    }
}
